"""COSMOS watermark metadata for generated artifacts."""

from __future__ import annotations

from datetime import datetime, timezone

__all__ = ("WATERMARK_HEADER", "apply_text_watermark", "watermark_footer")


WATERMARK_HEADER = "COSMOS 0.1 — COSMOS PVT LTD — TO INFINITY AND BEYOND"
WATERMARK_TAG = "Generated by COSMOS 0.1. Unauthorized redistribution prohibited."


def watermark_footer(*, user_id: str = "", login_id: str = "") -> str:
    stamp = datetime.now(timezone.utc).replace(microsecond=0).isoformat()
    actor = login_id or user_id or "unknown"
    return f"{WATERMARK_HEADER} | user={actor} | utc={stamp} | {WATERMARK_TAG}"


def apply_text_watermark(content: str, *, user_id: str = "", login_id: str = "") -> str:
    footer = watermark_footer(user_id=user_id, login_id=login_id)
    if footer in content:
        return content
    return f"{content.rstrip()}\n\n---\n{footer}\n"
